services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easyorder-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_USER_NAME: ${SPRING_SECURITY_USER_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_USER_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      RESET_DB: ${RESET_DB}
      TZ: Europe/Madrid
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    depends_on:
      - db
      - cache
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: easyorder-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
      VITE_FRONTEND_URL: ${VITE_FRONTEND_URL}
      VITE_WS_URL: ${VITE_WS_URL}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  db:
    image: mariadb:10.11-jammy
    container_name: easyorder-db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Madrid
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  cache:
    image: valkey/valkey:8.0-alpine
    container_name: easyorder-cache
    environment:
      TZ: Europe/Madrid
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data:
  maven_cache:
