-- =====================================================================================
-- SCRIPT DE MIGRACIÓN CONSOLIDADO: MARIADB -> POSTGRESQL (ESTÁNDAR SNAKE_CASE)
-- Usando: GENERATED BY DEFAULT AS IDENTITY
-- Incluye esquema base + migraciones (Tenant, Zonas de trabajo, Modificadores)
-- =====================================================================================

-- 0. Limpieza previa (opcional, útil para pruebas)
DROP TABLE IF EXISTS pedido_item_modificador CASCADE;
DROP TABLE IF EXISTS producto_grupo_modificador CASCADE;
DROP TABLE IF EXISTS modificador CASCADE;
DROP TABLE IF EXISTS grupo_modificador CASCADE;
DROP TABLE IF EXISTS token CASCADE;
DROP TABLE IF EXISTS pedido_item CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS pedido_estado CASCADE;
DROP TABLE IF EXISTS sesion CASCADE;
DROP TABLE IF EXISTS sesion_estado CASCADE;
DROP TABLE IF EXISTS producto_alergeno CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS producto_tipo CASCADE;
DROP TABLE IF EXISTS zona_trabajo CASCADE;
DROP TABLE IF EXISTS alergeno CASCADE;
DROP TABLE IF EXISTS ingrediente CASCADE;
DROP TABLE IF EXISTS unidad CASCADE;
DROP TABLE IF EXISTS mesa CASCADE;
DROP TABLE IF EXISTS mesa_estado CASCADE;
DROP TABLE IF EXISTS zona CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS usuario_rol CASCADE;
DROP TABLE IF EXISTS tenant CASCADE;

-- =====================================================================================
-- 1. CREACIÓN DE TABLAS (ORDENADAS POR DEPENDENCIAS)
-- =====================================================================================

CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    slug VARCHAR(60) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE alergeno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE unidad (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    simbolo VARCHAR(10) NOT NULL,
    factor INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ingrediente (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    stock DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (stock >= 0),
    id_unidad INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_ingrediente_unidad FOREIGN KEY (id_unidad) REFERENCES unidad (id) ON UPDATE CASCADE
);

CREATE TABLE zona_trabajo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE mesa_estado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE zona (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_zona_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id),
    CONSTRAINT uk_zona_tenant_nombre UNIQUE (id_tenant, nombre)
);

CREATE TABLE mesa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    numero INTEGER NOT NULL,
    id_estado BIGINT NOT NULL,
    id_zona BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mesa_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id),
    CONSTRAINT fk_mesa_estado FOREIGN KEY (id_estado) REFERENCES mesa_estado(id),
    CONSTRAINT fk_mesa_zona FOREIGN KEY (id_zona) REFERENCES zona(id),
    CONSTRAINT uk_mesa_tenant_numero UNIQUE (id_tenant, numero)
);

CREATE TABLE producto_tipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    id_zona_trabajo BIGINT,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(200),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_producto_tipo_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id),
    CONSTRAINT fk_producto_tipo_zona_trabajo FOREIGN KEY (id_zona_trabajo) REFERENCES zona_trabajo(id),
    CONSTRAINT uk_producto_tipo_tenant_nombre UNIQUE (id_tenant, nombre)
);

CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    disponible BOOLEAN NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    id_tipo BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(200),
    imagen VARCHAR(200),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_producto_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id),
    CONSTRAINT fk_producto_tipo FOREIGN KEY (id_tipo) REFERENCES producto_tipo(id),
    CONSTRAINT uk_producto_tenant_nombre UNIQUE (id_tenant, nombre)
);

CREATE TABLE producto_alergeno (
    id_producto BIGINT NOT NULL,
    id_alergeno BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL DEFAULT 'CONTIENE' CHECK (tipo IN ('CONTIENE', 'PUEDE_CONTENER_TRAZAS')),
    PRIMARY KEY (id_producto, id_alergeno),
    CONSTRAINT fk_producto_alergeno_producto FOREIGN KEY (id_producto) REFERENCES producto(id) ON DELETE CASCADE,
    CONSTRAINT fk_producto_alergeno_alergeno FOREIGN KEY (id_alergeno) REFERENCES alergeno(id) ON DELETE CASCADE
);
CREATE INDEX idx_producto_alergeno_producto ON producto_alergeno (id_producto);

CREATE TABLE usuario_rol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    activo BOOLEAN NOT NULL,
    rol BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    clave VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_usuario_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol) REFERENCES usuario_rol(id),
    CONSTRAINT uk_usuario_tenant_username UNIQUE (id_tenant, nombre)
);

CREATE TABLE sesion_estado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE sesion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    hora_fin TIMESTAMPTZ,
    hora_inicio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_estado BIGINT NOT NULL,
    id_mesa BIGINT NOT NULL,
    id_usuario BIGINT,
    qr_code_url VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_sesion_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id),
    CONSTRAINT fk_sesion_estado FOREIGN KEY (id_estado) REFERENCES sesion_estado(id),
    CONSTRAINT fk_sesion_mesa FOREIGN KEY (id_mesa) REFERENCES mesa(id),
    CONSTRAINT fk_sesion_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);

CREATE TABLE pedido_estado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    descripcion VARCHAR(200)
);

CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    id_estado BIGINT NOT NULL,
    id_sesion BIGINT NOT NULL,
    total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_pedido_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id),
    CONSTRAINT fk_pedido_estado FOREIGN KEY (id_estado) REFERENCES pedido_estado(id),
    CONSTRAINT fk_pedido_sesion FOREIGN KEY (id_sesion) REFERENCES sesion(id)
);

CREATE TABLE pedido_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario DECIMAL(10,2) NOT NULL,
    id_pedido BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    id_zona_trabajo BIGINT,
    listo_para_servir BOOLEAN,
    servido BOOLEAN DEFAULT FALSE,
    nota VARCHAR(200),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_pedido_item_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id),
    CONSTRAINT fk_pedido_item_producto FOREIGN KEY (id_producto) REFERENCES producto(id),
    CONSTRAINT fk_pedido_item_zona_trabajo FOREIGN KEY (id_zona_trabajo) REFERENCES zona_trabajo(id),
    CONSTRAINT fk_pedido_item_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    token VARCHAR(256) UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN DEFAULT FALSE NOT NULL,
    usuario_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_token_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_refresh_token_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id)
);

CREATE TABLE grupo_modificador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    seleccion_minima INTEGER NOT NULL DEFAULT 0,
    seleccion_maxima INTEGER NOT NULL DEFAULT 1,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_grupo_modificador_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id)

);

CREATE TABLE modificador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    id_grupo BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    precio_extra DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_modificador_grupo FOREIGN KEY (id_grupo) REFERENCES grupo_modificador (id),
    CONSTRAINT fk_modificador_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id)
);

CREATE TABLE producto_grupo_modificador (
    id_producto BIGINT NOT NULL,
    id_grupo BIGINT NOT NULL,
    orden_visual INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id_producto, id_grupo),
    CONSTRAINT fk_pgm_producto FOREIGN KEY (id_producto) REFERENCES producto (id),
    CONSTRAINT fk_pgm_grupo FOREIGN KEY (id_grupo) REFERENCES grupo_modificador (id)
);

CREATE TABLE pedido_item_modificador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tenant BIGINT NOT NULL,
    id_pedido_item BIGINT NOT NULL,
    id_modificador BIGINT NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_aplicado DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_pim_pedido_item FOREIGN KEY (id_pedido_item) REFERENCES pedido_item (id) ON DELETE CASCADE,
    CONSTRAINT fk_pim_modificador FOREIGN KEY (id_modificador) REFERENCES modificador (id),
    CONSTRAINT fk_pim_tenant FOREIGN KEY (id_tenant) REFERENCES tenant(id)
);


-- =====================================================================================
-- 2. INSERCIÓN DE DATOS INICIALES
-- =====================================================================================

INSERT INTO tenant (id, nombre, slug) VALUES 
(1, 'Casa Cele', 'casacele'),
(2, 'Futbolista', 'futbolista');

INSERT INTO zona_trabajo (id, nombre) VALUES 
(1, 'COCINA'), 
(2, 'BARRA');

INSERT INTO alergeno (id, nombre, descripcion) VALUES
(1, 'Gluten', 'Cereales que contienen gluten'),
(2, 'Crustáceos', 'Crustáceos y productos a base de crustáceos'),
(3, 'Huevos', 'Huevos y productos a base de huevo'),
(4, 'Pescado', 'Pescado y productos a base de pescado'),
(5, 'Cacahuetes', 'Cacahuetes y productos a base de cacahuetes'),
(6, 'Soja', 'Soja y productos a base de soja'),
(7, 'Leche', 'Leche y sus derivados (incluida la lactosa)'),
(8, 'Frutos de cáscara', 'Almendras, avellanas, nueces, anacardos, pacanas, nueces de Brasil, pistachos, nueces de macadamia y productos derivados'),
(9, 'Apio', 'Apio y productos derivados'),
(10, 'Mostaza', 'Mostaza y productos derivados'),
(11, 'Sésamo', 'Granos de sésamo y productos a base de granos de sésamo'),
(12, 'Sulfitos', 'Dióxido de azufre y sulfitos en concentraciones superiores a 10 mg/kg o 10 mg/litro'),
(13, 'Altramuces', 'Altramuces y productos a base de altramuces'),
(14, 'Moluscos', 'Moluscos y productos a base de moluscos');

INSERT INTO unidad (id, nombre, simbolo, factor) VALUES
(1, 'gramo', 'g', 1),
(2, 'kilogramo', 'kg', 1000),
(3, 'litro', 'L', 1000),
(4, 'mililitro', 'ml', 1),
(5, 'unidad', 'u', 1);

INSERT INTO mesa_estado (id, nombre) VALUES
(1, 'LIBRE'),
(2, 'OCUPADA'),
(3, 'ESPERANDO_PEDIDO'),
(4, 'ESPERANDO_CUENTA');

INSERT INTO zona (id, id_tenant, nombre, descripcion) VALUES
(1, 1, 'INTERIOR', NULL),
(2, 1, 'EXTERIOR', NULL);

INSERT INTO mesa (id, id_tenant, numero, id_estado, id_zona) VALUES
(1,1,1,1,1), (2,1,2,1,1), (3,1,3,1,1), (4,1,4,1,1), (6,1,5,1,1),
(7,1,6,1,2), (8,1,7,1,2), (9,1,8,1,2), (10,1,9,1,2), (12,1,10,1,2);

INSERT INTO producto_tipo (id, id_tenant, id_zona_trabajo, nombre, descripcion) VALUES
(1, 1, 1, 'TAPA', NULL),
(2, 1, 1, 'RACION', NULL),
(3, 1, 1, 'POSTRE', NULL),
(4, 1, 2, 'BEBIDA', NULL);

INSERT INTO producto (id, id_tenant, disponible, precio, id_tipo, nombre, descripcion, imagen) VALUES
(1, 1, TRUE, 1.50, 4, 'Agua grande', 'Botella de agua 1L', 'agua1.png'),
(2, 1, TRUE, 1.00, 4, 'Agua pequeña', 'Botella de agua 500ml', 'agua2.png'),
(3, 1, TRUE, 1.80, 4, 'Refresco', 'Bebida refrescante con gas', 'cola.jpg'),
(4, 1, TRUE, 2.50, 4, 'Cerveza', 'Cerveza fría de barril o botella', 'cerveza.png'),
(5, 1, TRUE, 3.00, 4, 'Vino', 'Copa de vino tinto', 'vino.png'),
(6, 1, TRUE, 2.50, 4, 'Tinto de verano', 'Vino con gaseosa y limón', 'tinto.png'),
(8, 1, TRUE, 1.80, 4, 'Zumo', 'Zumo natural de frutas', 'zumo.png'),
(9, 1, TRUE, 2.50, 1, 'Tortilla de patatas', 'Tapa tradicional española de patata y huevo', 'tortilla.jpg'),
(10, 1, TRUE, 2.80, 1, 'Croquetas caseras', 'Croquetas cremosas de jamón', 'croquetas.jpg'),
(11, 1, TRUE, 2.50, 1, 'Patatas bravas', 'Patatas fritas con salsa brava', 'bravas.png'),
(12, 1, TRUE, 2.50, 1, 'Ensaladilla rusa', 'Patata, atún, huevo y mayonesa', 'ensaladilla.png'),
(13, 1, TRUE, 3.20, 1, 'Calamares fritos', 'Anillas de calamar rebozadas', 'calamares.png'),
(14, 1, TRUE, 4.50, 2, 'Gambas al ajillo', 'Gambas salteadas con ajo y guindilla', 'gambas.jpg'),
(15, 1, TRUE, 5.50, 2, 'Jamón ibérico', 'Ración de jamón ibérico cortado a mano', 'jamon.jpg'),
(16, 1, TRUE, 4.00, 2, 'Queso curado', 'Tabla de queso curado de oveja', 'queso.jpg'),
(17, 1, TRUE, 4.50, 2, 'Huevos rotos', 'Patatas con huevos fritos y jamón', 'huevos.jpg'),
(18, 1, TRUE, 4.50, 2, 'Albóndigas', 'Albóndigas caseras en salsa de tomate', 'albondigas.jpg'),
(19, 1, TRUE, 2.50, 3, 'Flan de queso', 'Flan casero cremoso de queso', 'flan.png'),
(20, 1, TRUE, 1.80, 3, 'Yogur', 'Yogur natural o de sabores', 'yogur.jpg'),
(21, 1, TRUE, 2.00, 3, 'Natillas', 'Natillas caseras con canela', 'natillas.png'),
(22, 1, TRUE, 2.50, 3, 'Helado', 'Copa de helado variado', 'helado.jpg'),
(999, 1, TRUE, 4.50, 2, 'Hamburguesa', 'Hamburguesa casera con queso y patatas', 'food.png');

INSERT INTO producto_alergeno (id_producto, id_alergeno, tipo) VALUES
(4, 1, 'CONTIENE'),
(5, 12, 'CONTIENE'),
(6, 12, 'CONTIENE'),
(9, 3, 'CONTIENE'),
(10, 1, 'CONTIENE'), (10, 3, 'CONTIENE'), (10, 7, 'CONTIENE'),
(11, 1, 'PUEDE_CONTENER_TRAZAS'),
(12, 3, 'CONTIENE'), (12, 4, 'CONTIENE'),
(13, 1, 'CONTIENE'), (13, 14, 'CONTIENE'),
(14, 2, 'CONTIENE'),
(16, 7, 'CONTIENE'),
(17, 3, 'CONTIENE'),
(18, 1, 'CONTIENE'), (18, 3, 'CONTIENE'), (18, 7, 'CONTIENE'),
(19, 3, 'CONTIENE'), (19, 7, 'CONTIENE'),
(20, 7, 'CONTIENE'),
(21, 3, 'CONTIENE'), (21, 7, 'CONTIENE'),
(22, 7, 'CONTIENE'), (22, 8, 'PUEDE_CONTENER_TRAZAS');

INSERT INTO usuario_rol (id, nombre, descripcion) VALUES
(1, 'ADMIN', NULL),
(2, 'PERSONAL', NULL),
(3, 'COCINA', 'Rol para usuarios de estaciones en cocina (KDS)'),
(4, 'BARRA', 'Rol para usuarios de estaciones en barra');

INSERT INTO usuario (id, id_tenant, activo, created_at, rol, nombre, clave) VALUES
(1, 1, TRUE, '2026-04-24 12:32:49', 1, 'Mario', '$2a$10$92MiowW9DXGXAIR9N7IyKe/2y8ZQgHchsUi.UKV8Tsfd7loIpQfMG'),
(2, 2, TRUE, '2026-06-26 20:52:42', 1, 'tenant2', '$2a$10$2WMLVpuJIAtS2Rp8aWE5IuG3Vgdrbzz/o2W4ajpQ16KOSgCIo1fFq');

INSERT INTO sesion_estado (id, nombre, descripcion) VALUES
(1, 'ACTIVA', NULL),
(2, 'FINALIZADA', NULL),
(3, 'CANCELADA', NULL);

INSERT INTO pedido_estado (id, nombre, descripcion) VALUES
(1, 'PENDIENTE', NULL),
(2, 'PARCIAL', NULL),
(3, 'LISTO', NULL),
(4, 'SERVIDO', NULL),
(5, 'CANCELADO', NULL);

INSERT INTO grupo_modificador (id, id_tenant, nombre, seleccion_minima, seleccion_maxima, activo) VALUES 
(101, 1, 'Punto de carne', 1, 1, TRUE),
(102, 1, 'Extras', 0, 2, TRUE);

INSERT INTO modificador (id, id_tenant, id_grupo, nombre, precio_extra, activo) VALUES 
(1011, 1, 101, 'Poco hecha', 0.00, TRUE),
(1012, 1, 101, 'Al punto', 0.00, TRUE),
(1013, 1, 101, 'Muy hecha', 0.00, TRUE),
(1021, 1, 102, 'Extra Bacon', 1.00, TRUE),
(1022, 1, 102, 'Extra Queso', 1.00, TRUE);

INSERT INTO producto_grupo_modificador (id_producto, id_grupo, orden_visual) VALUES 
(999, 101, 1),
(999, 102, 2);

-- =====================================================================================
-- 3. ACTUALIZACIÓN DE LAS IDENTITIES (SECUENCIAS POSTGRESQL)
-- =====================================================================================

SELECT setval(pg_get_serial_sequence('tenant', 'id'), COALESCE(MAX(id), 1)) FROM tenant;
SELECT setval(pg_get_serial_sequence('alergeno', 'id'), COALESCE(MAX(id), 1)) FROM alergeno;
SELECT setval(pg_get_serial_sequence('unidad', 'id'), COALESCE(MAX(id), 1)) FROM unidad;
SELECT setval(pg_get_serial_sequence('zona_trabajo', 'id'), COALESCE(MAX(id), 1)) FROM zona_trabajo;
SELECT setval(pg_get_serial_sequence('mesa_estado', 'id'), COALESCE(MAX(id), 1)) FROM mesa_estado;
SELECT setval(pg_get_serial_sequence('zona', 'id'), COALESCE(MAX(id), 1)) FROM zona;
SELECT setval(pg_get_serial_sequence('mesa', 'id'), COALESCE(MAX(id), 1)) FROM mesa;
SELECT setval(pg_get_serial_sequence('producto_tipo', 'id'), COALESCE(MAX(id), 1)) FROM producto_tipo;
SELECT setval(pg_get_serial_sequence('producto', 'id'), COALESCE(MAX(id), 1)) FROM producto;
SELECT setval(pg_get_serial_sequence('usuario_rol', 'id'), COALESCE(MAX(id), 1)) FROM usuario_rol;
SELECT setval(pg_get_serial_sequence('usuario', 'id'), COALESCE(MAX(id), 1)) FROM usuario;
SELECT setval(pg_get_serial_sequence('sesion_estado', 'id'), COALESCE(MAX(id), 1)) FROM sesion_estado;
SELECT setval(pg_get_serial_sequence('pedido_estado', 'id'), COALESCE(MAX(id), 1)) FROM pedido_estado;
SELECT setval(pg_get_serial_sequence('grupo_modificador', 'id'), COALESCE(MAX(id), 1)) FROM grupo_modificador;
SELECT setval(pg_get_serial_sequence('modificador', 'id'), COALESCE(MAX(id), 1)) FROM modificador;